ALTER TABLE patients ALTER COLUMN phone TYPE CHAR(12);
ALTER TABLE doctors ALTER COLUMN phone TYPE CHAR(12);

ALTER TABLE patients ALTER COLUMN email TYPE VARCHAR(50);
ALTER TABLE doctors ALTER COLUMN email TYPE VARCHAR(50);

ALTER TABLE patients ALTER COLUMN insurance_number TYPE VARCHAR(20);

ALTER TABLE appointments ALTER COLUMN status TYPE VARCHAR(15);
ALTER TABLE payments ALTER COLUMN status TYPE VARCHAR(15);
